# app.yaml

runtime: python39
env: standard
entrypoint: gunicorn -b :$PORT core.wsgi:application

handlers:
  - url: /static              # new
    static_dir: static/       # new
  - url: /media               # new
    static_dir: media/        # new
  - url: /.*
    script: auto

runtime_config:
  python_version: 3

env_variables:
  APPENGINE_URL: thewypharma.com