# Generated by Django 4.2.7 on 2023-12-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_alter_paymentorder_order_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentOrder',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='created_at',
        ),
    ]
