# Generated by Django 4.0.3 on 2023-12-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_alter_paymentorder_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-12-07 19:43:07.376710+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-12-07 19:43:07.374874+05:30'),
        ),
    ]
