# Generated by Django 4.0.3 on 2023-12-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0006_alter_paymentorder_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-12-14 15:30:25.095262+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-12-14 15:30:25.093295+05:30'),
        ),
    ]
