<<<<<<< HEAD
# Generated by Django 4.0.3 on 2023-12-06 06:50
=======
# Generated by Django 4.2.7 on 2023-12-14 11:55
>>>>>>> fd6eed294ea19191cf011032393645223c25d2e6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogs',
            name='date_time',
<<<<<<< HEAD
            field=models.TextField(default='2023-12-06 12:20:11.635337+05:30'),
=======
            field=models.TextField(default='2023-12-14 17:25:40.364178+05:30'),
>>>>>>> fd6eed294ea19191cf011032393645223c25d2e6
        ),
    ]
