# Generated by Django 4.2.7 on 2023-12-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogs',
            name='date_time',
            field=models.TextField(default='2023-12-14 17:25:40.364178+05:30'),
        ),
    ]
