# Generated by Django 4.2.7 on 2023-12-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apiApp', '0002_alter_actionlogs_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogs',
            name='date_time',
            field=models.TextField(default='2023-12-14 17:31:05.495951+05:30'),
        ),
    ]
