<<<<<<< HEAD
# Generated by Django 4.0.3 on 2023-12-07 14:11
=======
# Generated by Django 4.2.7 on 2023-12-14 12:01
>>>>>>> fd6eed294ea19191cf011032393645223c25d2e6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apiApp', '0002_alter_actionlogs_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogs',
            name='date_time',
<<<<<<< HEAD
            field=models.TextField(default='2023-12-07 19:41:22.867197+05:30'),
=======
            field=models.TextField(default='2023-12-14 17:31:05.495951+05:30'),
>>>>>>> fd6eed294ea19191cf011032393645223c25d2e6
        ),
    ]
