# Generated by Django 4.0.3 on 2023-12-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_apiApp', '0007_alter_actionlogs_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogs',
            name='date_time',
            field=models.TextField(default='2023-12-14 22:39:11.503251+05:30'),
        ),
    ]
